%% Login error codes
-define(ce_success, 0).
-define(ce_ipban, 1).
-define(ce_account_closed, 3).
-define(ce_no_account, 4).
-define(ce_account_in_use, 6).
-define(ce_preorder_time_limit, 7).
-define(ce_server_full, 8).
-define(ce_wrong_build_number, 9).
-define(ce_update_client, 10).
-define(ce_account_freezed, 12).
